#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Projekt.Resource", IsApplication=true)]

namespace Projekt
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int im1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int im10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int im11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int im12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int im13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int im14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int im15 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int im2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int im3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int im4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int im5 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int im6 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int im7 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int im8 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int im9 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int original = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int table = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int closeGameButton = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int im1 = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int im10 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int im11 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int im12 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int im13 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int im14 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int im15 = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int im2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int im3 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int im4 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int im5 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int im6 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int im7 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int im8 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int im9 = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int logo = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int newGameButton = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int shakeButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int solveButton = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int table = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Image1Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
