# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UserRegistrationExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserRegistrationExample

  # this line is added 
  pod 'Alamofire', '~> 4.3'

  target 'UserRegistrationExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UserRegistrationExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
