#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChessGame.Resource", IsApplication=true)]

namespace ChessGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int ErrorEditTxt = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int backgroundColor = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int colorControlActivated = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int colorControlNormal = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int primaryColor = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int primaryColorDark = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int primaryColorLight = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int secondaryColor = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int secondaryColorDark = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int secondaryColorLight = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int black_square = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Chess_bdt60 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Chess_blt60 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Chess_kdt60 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Chess_klt60 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Chess_ndt60 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Chess_nlt60 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Chess_pdt60 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Chess_plt60 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Chess_qdt60 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Chess_qlt60 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Chess_rdt60 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Chess_rlt60 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int white_square = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07004e
			public const int BtnLogin = 2131165262;
			
			// aapt resource value: 0x7f070050
			public const int BtnRegister = 2131165264;
			
			// aapt resource value: 0x7f07004d
			public const int EditTxtPassword = 2131165261;
			
			// aapt resource value: 0x7f07004c
			public const int EditTxtUsername = 2131165260;
			
			// aapt resource value: 0x7f070001
			public const int GameBoard = 2131165185;
			
			// aapt resource value: 0x7f07004a
			public const int GameMenu = 2131165258;
			
			// aapt resource value: 0x7f070000
			public const int GameUndo = 2131165184;
			
			// aapt resource value: 0x7f070053
			public const int LandingBtn = 2131165267;
			
			// aapt resource value: 0x7f070052
			public const int LandingDescription = 2131165266;
			
			// aapt resource value: 0x7f070051
			public const int LandingHeader = 2131165265;
			
			// aapt resource value: 0x7f070056
			public const int MenuContinue = 2131165270;
			
			// aapt resource value: 0x7f070058
			public const int MenuLogout = 2131165272;
			
			// aapt resource value: 0x7f070055
			public const int MenuNewGame = 2131165269;
			
			// aapt resource value: 0x7f070057
			public const int MenuSaveGame = 2131165271;
			
			// aapt resource value: 0x7f07005e
			public const int RegisterBack = 2131165278;
			
			// aapt resource value: 0x7f07005d
			public const int RegisterConfirm = 2131165277;
			
			// aapt resource value: 0x7f070059
			public const int RegisterErrors = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int RegisterName = 2131165274;
			
			// aapt resource value: 0x7f07005c
			public const int RegisterPassword = 2131165276;
			
			// aapt resource value: 0x7f07005b
			public const int RegisterUsername = 2131165275;
			
			// aapt resource value: 0x7f07004b
			public const int TxtViewLoginErrors = 2131165259;
			
			// aapt resource value: 0x7f07004f
			public const int TxtViewOr = 2131165263;
			
			// aapt resource value: 0x7f070005
			public const int imageView1 = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int imageView10 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int imageView11 = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int imageView13 = 2131165207;
			
			// aapt resource value: 0x7f070020
			public const int imageView14 = 2131165216;
			
			// aapt resource value: 0x7f070029
			public const int imageView15 = 2131165225;
			
			// aapt resource value: 0x7f070032
			public const int imageView16 = 2131165234;
			
			// aapt resource value: 0x7f07003b
			public const int imageView17 = 2131165243;
			
			// aapt resource value: 0x7f070043
			public const int imageView18 = 2131165251;
			
			// aapt resource value: 0x7f07003a
			public const int imageView19 = 2131165242;
			
			// aapt resource value: 0x7f070006
			public const int imageView2 = 2131165190;
			
			// aapt resource value: 0x7f070031
			public const int imageView20 = 2131165233;
			
			// aapt resource value: 0x7f070028
			public const int imageView21 = 2131165224;
			
			// aapt resource value: 0x7f07001f
			public const int imageView22 = 2131165215;
			
			// aapt resource value: 0x7f070016
			public const int imageView23 = 2131165206;
			
			// aapt resource value: 0x7f07000d
			public const int imageView24 = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int imageView25 = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int imageView26 = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int imageView27 = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int imageView28 = 2131165205;
			
			// aapt resource value: 0x7f07001e
			public const int imageView29 = 2131165214;
			
			// aapt resource value: 0x7f070007
			public const int imageView3 = 2131165191;
			
			// aapt resource value: 0x7f070027
			public const int imageView30 = 2131165223;
			
			// aapt resource value: 0x7f070030
			public const int imageView31 = 2131165232;
			
			// aapt resource value: 0x7f070039
			public const int imageView32 = 2131165241;
			
			// aapt resource value: 0x7f070042
			public const int imageView33 = 2131165250;
			
			// aapt resource value: 0x7f070044
			public const int imageView34 = 2131165252;
			
			// aapt resource value: 0x7f070018
			public const int imageView35 = 2131165208;
			
			// aapt resource value: 0x7f070021
			public const int imageView36 = 2131165217;
			
			// aapt resource value: 0x7f07002a
			public const int imageView37 = 2131165226;
			
			// aapt resource value: 0x7f070033
			public const int imageView38 = 2131165235;
			
			// aapt resource value: 0x7f07003c
			public const int imageView39 = 2131165244;
			
			// aapt resource value: 0x7f070008
			public const int imageView4 = 2131165192;
			
			// aapt resource value: 0x7f070045
			public const int imageView40 = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int imageView41 = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int imageView42 = 2131165255;
			
			// aapt resource value: 0x7f07003d
			public const int imageView43 = 2131165245;
			
			// aapt resource value: 0x7f070034
			public const int imageView44 = 2131165236;
			
			// aapt resource value: 0x7f07002b
			public const int imageView45 = 2131165227;
			
			// aapt resource value: 0x7f070022
			public const int imageView46 = 2131165218;
			
			// aapt resource value: 0x7f070019
			public const int imageView47 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int imageView48 = 2131165210;
			
			// aapt resource value: 0x7f070023
			public const int imageView49 = 2131165219;
			
			// aapt resource value: 0x7f070012
			public const int imageView5 = 2131165202;
			
			// aapt resource value: 0x7f07002c
			public const int imageView50 = 2131165228;
			
			// aapt resource value: 0x7f070035
			public const int imageView51 = 2131165237;
			
			// aapt resource value: 0x7f07003e
			public const int imageView52 = 2131165246;
			
			// aapt resource value: 0x7f07001c
			public const int imageView53 = 2131165212;
			
			// aapt resource value: 0x7f070025
			public const int imageView54 = 2131165221;
			
			// aapt resource value: 0x7f07002e
			public const int imageView55 = 2131165230;
			
			// aapt resource value: 0x7f070037
			public const int imageView56 = 2131165239;
			
			// aapt resource value: 0x7f070040
			public const int imageView57 = 2131165248;
			
			// aapt resource value: 0x7f070049
			public const int imageView58 = 2131165257;
			
			// aapt resource value: 0x7f070048
			public const int imageView59 = 2131165256;
			
			// aapt resource value: 0x7f070009
			public const int imageView6 = 2131165193;
			
			// aapt resource value: 0x7f07003f
			public const int imageView60 = 2131165247;
			
			// aapt resource value: 0x7f070036
			public const int imageView61 = 2131165238;
			
			// aapt resource value: 0x7f07002d
			public const int imageView62 = 2131165229;
			
			// aapt resource value: 0x7f070024
			public const int imageView63 = 2131165220;
			
			// aapt resource value: 0x7f07001b
			public const int imageView64 = 2131165211;
			
			// aapt resource value: 0x7f07000a
			public const int imageView65 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int imageView7 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int imageView8 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int imageView9 = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int tableRow1 = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow2 = 2131165195;
			
			// aapt resource value: 0x7f070014
			public const int tableRow3 = 2131165204;
			
			// aapt resource value: 0x7f07001d
			public const int tableRow4 = 2131165213;
			
			// aapt resource value: 0x7f070026
			public const int tableRow5 = 2131165222;
			
			// aapt resource value: 0x7f07002f
			public const int tableRow6 = 2131165231;
			
			// aapt resource value: 0x7f070038
			public const int tableRow7 = 2131165240;
			
			// aapt resource value: 0x7f070041
			public const int tableRow8 = 2131165249;
			
			// aapt resource value: 0x7f070054
			public const int textView1 = 2131165268;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Register = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f05001a
			public const int GameMenu = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int GameUndo = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int GameUndoDone = 2131034137;
			
			// aapt resource value: 0x7f050005
			public const int LoginBtnLogin = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int LoginBtnRegister = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int LoginEditTxtPassword = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int LoginEditTxtUsername = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int LoginErrorRequired = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int LoginErrorWrong = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int LoginTxtViewOr = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int MainCreator = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int MenuContinue = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int MenuLogout = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int MenuNewGame = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int MenuSaveGame = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int MenuSaveSuccess = 2131034135;
			
			// aapt resource value: 0x7f050010
			public const int RegisterBack = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int RegisterConfirm = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int RegisterErrorExists = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int RegisterErrorRequired = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int RegisterName = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int RegisterPassword = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int RegisterUsername = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int landingBtn = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int landingDetails = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int landingHeader = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_ChessBlue = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
