#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GettingStarted.Resource", IsApplication=true)]

namespace GettingStarted
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.Data.Resource.String.library_name = global::GettingStarted.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowDraggingColumn = global::GettingStarted.Resource.Attribute.allowDraggingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowDraggingRow = global::GettingStarted.Resource.Attribute.allowDraggingRow;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowEditing = global::GettingStarted.Resource.Attribute.allowEditing;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowGroupExpandCollapse = global::GettingStarted.Resource.Attribute.allowGroupExpandCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowLoadMore = global::GettingStarted.Resource.Attribute.allowLoadMore;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowMultiSorting = global::GettingStarted.Resource.Attribute.allowMultiSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowNull = global::GettingStarted.Resource.Attribute.allowNull;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowPullToRefresh = global::GettingStarted.Resource.Attribute.allowPullToRefresh;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowResizingColumn = global::GettingStarted.Resource.Attribute.allowResizingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowSorting = global::GettingStarted.Resource.Attribute.allowSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowSwiping = global::GettingStarted.Resource.Attribute.allowSwiping;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowTriStateSorting = global::GettingStarted.Resource.Attribute.allowTriStateSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.alternationCount = global::GettingStarted.Resource.Attribute.alternationCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.autoExpandGroups = global::GettingStarted.Resource.Attribute.autoExpandGroups;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.autoGenerateColumns = global::GettingStarted.Resource.Attribute.autoGenerateColumns;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.borderColor = global::GettingStarted.Resource.Attribute.borderColor;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.columnSizer = global::GettingStarted.Resource.Attribute.columnSizer;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.culture = global::GettingStarted.Resource.Attribute.culture;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.editTapAction = global::GettingStarted.Resource.Attribute.editTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.editorSelectionBehavior = global::GettingStarted.Resource.Attribute.editorSelectionBehavior;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.enableGroupSeparator = global::GettingStarted.Resource.Attribute.enableGroupSeparator;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.fontSize = global::GettingStarted.Resource.Attribute.fontSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.frozenColumnsCount = global::GettingStarted.Resource.Attribute.frozenColumnsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.frozenRowsCount = global::GettingStarted.Resource.Attribute.frozenRowsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.gridRowHeight = global::GettingStarted.Resource.Attribute.gridRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.gridSelectionMode = global::GettingStarted.Resource.Attribute.gridSelectionMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.groupingMode = global::GettingStarted.Resource.Attribute.groupingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.headerRowHeight = global::GettingStarted.Resource.Attribute.headerRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.indentColumnWidth = global::GettingStarted.Resource.Attribute.indentColumnWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.isBusy = global::GettingStarted.Resource.Attribute.isBusy;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.loadMorePosition = global::GettingStarted.Resource.Attribute.loadMorePosition;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.loadMoreText = global::GettingStarted.Resource.Attribute.loadMoreText;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.maxSwipeOffset = global::GettingStarted.Resource.Attribute.maxSwipeOffset;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.maximumDecimalDigits = global::GettingStarted.Resource.Attribute.maximumDecimalDigits;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numberFormat = global::GettingStarted.Resource.Attribute.numberFormat;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numericButtonBackground = global::GettingStarted.Resource.Attribute.numericButtonBackground;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numericButtonCount = global::GettingStarted.Resource.Attribute.numericButtonCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numericTextBoxValue = global::GettingStarted.Resource.Attribute.numericTextBoxValue;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.orientation = global::GettingStarted.Resource.Attribute.orientation;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.pageCount = global::GettingStarted.Resource.Attribute.pageCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.pageSize = global::GettingStarted.Resource.Attribute.pageSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.parsingMode = global::GettingStarted.Resource.Attribute.parsingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.percentDisplayMode = global::GettingStarted.Resource.Attribute.percentDisplayMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.resizingMode = global::GettingStarted.Resource.Attribute.resizingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.rowHeaderWidth = global::GettingStarted.Resource.Attribute.rowHeaderWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.scrollingMode = global::GettingStarted.Resource.Attribute.scrollingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.selectAllOnFocus = global::GettingStarted.Resource.Attribute.selectAllOnFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.selectedIndex = global::GettingStarted.Resource.Attribute.selectedIndex;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.selectionForeground = global::GettingStarted.Resource.Attribute.selectionForeground;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.showRowHeader = global::GettingStarted.Resource.Attribute.showRowHeader;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.sortTapAction = global::GettingStarted.Resource.Attribute.sortTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.useOnDemandPaging = global::GettingStarted.Resource.Attribute.useOnDemandPaging;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.valueChangeMode = global::GettingStarted.Resource.Attribute.valueChangeMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.verticalOverScrollMode = global::GettingStarted.Resource.Attribute.verticalOverScrollMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.watermark = global::GettingStarted.Resource.Attribute.watermark;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.watermarkColor = global::GettingStarted.Resource.Attribute.watermarkColor;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Ascending = global::GettingStarted.Resource.Drawable.Ascending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Descending = global::GettingStarted.Resource.Drawable.Descending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Drag_and_Drop_Icon = global::GettingStarted.Resource.Drawable.Drag_and_Drop_Icon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragDown = global::GettingStarted.Resource.Drawable.DragDown;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragUp = global::GettingStarted.Resource.Drawable.DragUp;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.error2 = global::GettingStarted.Resource.Drawable.error2;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.FirstPageIcon = global::GettingStarted.Resource.Drawable.FirstPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupCollapse = global::GettingStarted.Resource.Drawable.GroupCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupExpander = global::GettingStarted.Resource.Drawable.GroupExpander;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupIcon_Android = global::GettingStarted.Resource.Drawable.GroupIcon_Android;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.LastPageIcon = global::GettingStarted.Resource.Drawable.LastPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.NextPageIcon = global::GettingStarted.Resource.Drawable.NextPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.PrevPageIcon = global::GettingStarted.Resource.Drawable.PrevPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.ResizingIcon = global::GettingStarted.Resource.Drawable.ResizingIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Sort = global::GettingStarted.Resource.Drawable.Sort;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.SortDescending = global::GettingStarted.Resource.Drawable.SortDescending;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.auto = global::GettingStarted.Resource.Id.auto;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.bottom = global::GettingStarted.Resource.Id.bottom;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.bounce = global::GettingStarted.Resource.Id.bounce;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.compute = global::GettingStarted.Resource.Id.compute;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.decimalMode = global::GettingStarted.Resource.Id.decimalMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.doubleMode = global::GettingStarted.Resource.Id.doubleMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.doubleTap = global::GettingStarted.Resource.Id.doubleTap;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.horizontal = global::GettingStarted.Resource.Id.horizontal;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.lastCoulmnFill = global::GettingStarted.Resource.Id.lastCoulmnFill;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.line = global::GettingStarted.Resource.Id.line;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.moveLast = global::GettingStarted.Resource.Id.moveLast;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.multiple = global::GettingStarted.Resource.Id.multiple;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.none = global::GettingStarted.Resource.Id.none;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onKeyFocus = global::GettingStarted.Resource.Id.onKeyFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onLostFocus = global::GettingStarted.Resource.Id.onLostFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onMoved = global::GettingStarted.Resource.Id.onMoved;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onTap = global::GettingStarted.Resource.Id.onTap;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onTouchUp = global::GettingStarted.Resource.Id.onTouchUp;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.pixel = global::GettingStarted.Resource.Id.pixel;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.pixelLine = global::GettingStarted.Resource.Id.pixelLine;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.selectAll = global::GettingStarted.Resource.Id.selectAll;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.single = global::GettingStarted.Resource.Id.single;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.singleDeSelect = global::GettingStarted.Resource.Id.singleDeSelect;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.singleTap = global::GettingStarted.Resource.Id.singleTap;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.star = global::GettingStarted.Resource.Id.star;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.top = global::GettingStarted.Resource.Id.top;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.value = global::GettingStarted.Resource.Id.value;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.vertical = global::GettingStarted.Resource.Id.vertical;
			global::Syncfusion.SfDataGrid.Android.Resource.Layout.ScrollViewer = global::GettingStarted.Resource.Layout.ScrollViewer;
			global::Syncfusion.SfDataGrid.Android.Resource.String.library_name = global::GettingStarted.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid = global::GettingStarted.Resource.Styleable.SfDataGrid;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowDraggingColumn = global::GettingStarted.Resource.Styleable.SfDataGrid_allowDraggingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowDraggingRow = global::GettingStarted.Resource.Styleable.SfDataGrid_allowDraggingRow;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowEditing = global::GettingStarted.Resource.Styleable.SfDataGrid_allowEditing;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowGroupExpandCollapse = global::GettingStarted.Resource.Styleable.SfDataGrid_allowGroupExpandCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowLoadMore = global::GettingStarted.Resource.Styleable.SfDataGrid_allowLoadMore;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowMultiSorting = global::GettingStarted.Resource.Styleable.SfDataGrid_allowMultiSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowPullToRefresh = global::GettingStarted.Resource.Styleable.SfDataGrid_allowPullToRefresh;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowResizingColumn = global::GettingStarted.Resource.Styleable.SfDataGrid_allowResizingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowSorting = global::GettingStarted.Resource.Styleable.SfDataGrid_allowSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowSwiping = global::GettingStarted.Resource.Styleable.SfDataGrid_allowSwiping;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowTriStateSorting = global::GettingStarted.Resource.Styleable.SfDataGrid_allowTriStateSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_alternationCount = global::GettingStarted.Resource.Styleable.SfDataGrid_alternationCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_autoExpandGroups = global::GettingStarted.Resource.Styleable.SfDataGrid_autoExpandGroups;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_autoGenerateColumns = global::GettingStarted.Resource.Styleable.SfDataGrid_autoGenerateColumns;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_columnSizer = global::GettingStarted.Resource.Styleable.SfDataGrid_columnSizer;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_editTapAction = global::GettingStarted.Resource.Styleable.SfDataGrid_editTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_editorSelectionBehavior = global::GettingStarted.Resource.Styleable.SfDataGrid_editorSelectionBehavior;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_frozenColumnsCount = global::GettingStarted.Resource.Styleable.SfDataGrid_frozenColumnsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_frozenRowsCount = global::GettingStarted.Resource.Styleable.SfDataGrid_frozenRowsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_gridRowHeight = global::GettingStarted.Resource.Styleable.SfDataGrid_gridRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_gridSelectionMode = global::GettingStarted.Resource.Styleable.SfDataGrid_gridSelectionMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_groupingMode = global::GettingStarted.Resource.Styleable.SfDataGrid_groupingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_headerRowHeight = global::GettingStarted.Resource.Styleable.SfDataGrid_headerRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_indentColumnWidth = global::GettingStarted.Resource.Styleable.SfDataGrid_indentColumnWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_isBusy = global::GettingStarted.Resource.Styleable.SfDataGrid_isBusy;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_loadMorePosition = global::GettingStarted.Resource.Styleable.SfDataGrid_loadMorePosition;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_loadMoreText = global::GettingStarted.Resource.Styleable.SfDataGrid_loadMoreText;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_maxSwipeOffset = global::GettingStarted.Resource.Styleable.SfDataGrid_maxSwipeOffset;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_resizingMode = global::GettingStarted.Resource.Styleable.SfDataGrid_resizingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_rowHeaderWidth = global::GettingStarted.Resource.Styleable.SfDataGrid_rowHeaderWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_scrollingMode = global::GettingStarted.Resource.Styleable.SfDataGrid_scrollingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_selectedIndex = global::GettingStarted.Resource.Styleable.SfDataGrid_selectedIndex;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_showRowHeader = global::GettingStarted.Resource.Styleable.SfDataGrid_showRowHeader;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_sortTapAction = global::GettingStarted.Resource.Styleable.SfDataGrid_sortTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_verticalOverScrollMode = global::GettingStarted.Resource.Styleable.SfDataGrid_verticalOverScrollMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager = global::GettingStarted.Resource.Styleable.SfDataPager;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_numericButtonBackground = global::GettingStarted.Resource.Styleable.SfDataPager_numericButtonBackground;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_numericButtonCount = global::GettingStarted.Resource.Styleable.SfDataPager_numericButtonCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_orientation = global::GettingStarted.Resource.Styleable.SfDataPager_orientation;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_pageCount = global::GettingStarted.Resource.Styleable.SfDataPager_pageCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_pageSize = global::GettingStarted.Resource.Styleable.SfDataPager_pageSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_selectionForeground = global::GettingStarted.Resource.Styleable.SfDataPager_selectionForeground;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_useOnDemandPaging = global::GettingStarted.Resource.Styleable.SfDataPager_useOnDemandPaging;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox = global::GettingStarted.Resource.Styleable.SfNumericTextBox;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_allowNull = global::GettingStarted.Resource.Styleable.SfNumericTextBox_allowNull;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_borderColor = global::GettingStarted.Resource.Styleable.SfNumericTextBox_borderColor;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_culture = global::GettingStarted.Resource.Styleable.SfNumericTextBox_culture;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_enableGroupSeparator = global::GettingStarted.Resource.Styleable.SfNumericTextBox_enableGroupSeparator;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_fontSize = global::GettingStarted.Resource.Styleable.SfNumericTextBox_fontSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits = global::GettingStarted.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_numberFormat = global::GettingStarted.Resource.Styleable.SfNumericTextBox_numberFormat;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_numericTextBoxValue = global::GettingStarted.Resource.Styleable.SfNumericTextBox_numericTextBoxValue;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_parsingMode = global::GettingStarted.Resource.Styleable.SfNumericTextBox_parsingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_percentDisplayMode = global::GettingStarted.Resource.Styleable.SfNumericTextBox_percentDisplayMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_selectAllOnFocus = global::GettingStarted.Resource.Styleable.SfNumericTextBox_selectAllOnFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_valueChangeMode = global::GettingStarted.Resource.Styleable.SfNumericTextBox_valueChangeMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_watermark = global::GettingStarted.Resource.Styleable.SfNumericTextBox_watermark;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_watermarkColor = global::GettingStarted.Resource.Styleable.SfNumericTextBox_watermarkColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.allowNull = global::GettingStarted.Resource.Attribute.allowNull;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.borderColor = global::GettingStarted.Resource.Attribute.borderColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.culture = global::GettingStarted.Resource.Attribute.culture;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.enableGroupSeparator = global::GettingStarted.Resource.Attribute.enableGroupSeparator;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.fontSize = global::GettingStarted.Resource.Attribute.fontSize;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.maximumDecimalDigits = global::GettingStarted.Resource.Attribute.maximumDecimalDigits;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.numberFormat = global::GettingStarted.Resource.Attribute.numberFormat;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.numericTextBoxValue = global::GettingStarted.Resource.Attribute.numericTextBoxValue;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.parsingMode = global::GettingStarted.Resource.Attribute.parsingMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.percentDisplayMode = global::GettingStarted.Resource.Attribute.percentDisplayMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.selectAllOnFocus = global::GettingStarted.Resource.Attribute.selectAllOnFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.valueChangeMode = global::GettingStarted.Resource.Attribute.valueChangeMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.watermark = global::GettingStarted.Resource.Attribute.watermark;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.watermarkColor = global::GettingStarted.Resource.Attribute.watermarkColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.compute = global::GettingStarted.Resource.Id.compute;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.decimalMode = global::GettingStarted.Resource.Id.decimalMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.doubleMode = global::GettingStarted.Resource.Id.doubleMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.onKeyFocus = global::GettingStarted.Resource.Id.onKeyFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.onLostFocus = global::GettingStarted.Resource.Id.onLostFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.value = global::GettingStarted.Resource.Id.value;
			global::Com.Syncfusion.Numerictextbox.Resource.String.library_name = global::GettingStarted.Resource.String.library_name;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox = global::GettingStarted.Resource.Styleable.SfNumericTextBox;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_allowNull = global::GettingStarted.Resource.Styleable.SfNumericTextBox_allowNull;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_borderColor = global::GettingStarted.Resource.Styleable.SfNumericTextBox_borderColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_culture = global::GettingStarted.Resource.Styleable.SfNumericTextBox_culture;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_enableGroupSeparator = global::GettingStarted.Resource.Styleable.SfNumericTextBox_enableGroupSeparator;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_fontSize = global::GettingStarted.Resource.Styleable.SfNumericTextBox_fontSize;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits = global::GettingStarted.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_numberFormat = global::GettingStarted.Resource.Styleable.SfNumericTextBox_numberFormat;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_numericTextBoxValue = global::GettingStarted.Resource.Styleable.SfNumericTextBox_numericTextBoxValue;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_parsingMode = global::GettingStarted.Resource.Styleable.SfNumericTextBox_parsingMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_percentDisplayMode = global::GettingStarted.Resource.Styleable.SfNumericTextBox_percentDisplayMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_selectAllOnFocus = global::GettingStarted.Resource.Styleable.SfNumericTextBox_selectAllOnFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_valueChangeMode = global::GettingStarted.Resource.Styleable.SfNumericTextBox_valueChangeMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_watermark = global::GettingStarted.Resource.Styleable.SfNumericTextBox_watermark;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_watermarkColor = global::GettingStarted.Resource.Styleable.SfNumericTextBox_watermarkColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010028
			public const int allowDraggingColumn = 2130772008;
			
			// aapt resource value: 0x7f01002a
			public const int allowDraggingRow = 2130772010;
			
			// aapt resource value: 0x7f01001b
			public const int allowEditing = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int allowGroupExpandCollapse = 2130771994;
			
			// aapt resource value: 0x7f010023
			public const int allowLoadMore = 2130772003;
			
			// aapt resource value: 0x7f010016
			public const int allowMultiSorting = 2130771990;
			
			// aapt resource value: 0x7f010009
			public const int allowNull = 2130771977;
			
			// aapt resource value: 0x7f010026
			public const int allowPullToRefresh = 2130772006;
			
			// aapt resource value: 0x7f010010
			public const int allowResizingColumn = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int allowSorting = 2130771988;
			
			// aapt resource value: 0x7f01002c
			public const int allowSwiping = 2130772012;
			
			// aapt resource value: 0x7f010015
			public const int allowTriStateSorting = 2130771989;
			
			// aapt resource value: 0x7f010022
			public const int alternationCount = 2130772002;
			
			// aapt resource value: 0x7f010019
			public const int autoExpandGroups = 2130771993;
			
			// aapt resource value: 0x7f01000e
			public const int autoGenerateColumns = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int borderColor = 2130771978;
			
			// aapt resource value: 0x7f01002e
			public const int columnSizer = 2130772014;
			
			// aapt resource value: 0x7f01000c
			public const int culture = 2130771980;
			
			// aapt resource value: 0x7f01001c
			public const int editTapAction = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int editorSelectionBehavior = 2130771997;
			
			// aapt resource value: 0x7f010003
			public const int enableGroupSeparator = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int fontSize = 2130771976;
			
			// aapt resource value: 0x7f010029
			public const int frozenColumnsCount = 2130772009;
			
			// aapt resource value: 0x7f01002b
			public const int frozenRowsCount = 2130772011;
			
			// aapt resource value: 0x7f01002f
			public const int gridRowHeight = 2130772015;
			
			// aapt resource value: 0x7f01001e
			public const int gridSelectionMode = 2130771998;
			
			// aapt resource value: 0x7f010018
			public const int groupingMode = 2130771992;
			
			// aapt resource value: 0x7f010030
			public const int headerRowHeight = 2130772016;
			
			// aapt resource value: 0x7f01000f
			public const int indentColumnWidth = 2130771983;
			
			// aapt resource value: 0x7f010027
			public const int isBusy = 2130772007;
			
			// aapt resource value: 0x7f010025
			public const int loadMorePosition = 2130772005;
			
			// aapt resource value: 0x7f010024
			public const int loadMoreText = 2130772004;
			
			// aapt resource value: 0x7f01002d
			public const int maxSwipeOffset = 2130772013;
			
			// aapt resource value: 0x7f010006
			public const int maximumDecimalDigits = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int numberFormat = 2130771972;
			
			// aapt resource value: 0x7f010036
			public const int numericButtonBackground = 2130772022;
			
			// aapt resource value: 0x7f010031
			public const int numericButtonCount = 2130772017;
			
			// aapt resource value: 0x7f01000d
			public const int numericTextBoxValue = 2130771981;
			
			// aapt resource value: 0x7f010034
			public const int orientation = 2130772020;
			
			// aapt resource value: 0x7f010033
			public const int pageCount = 2130772019;
			
			// aapt resource value: 0x7f010032
			public const int pageSize = 2130772018;
			
			// aapt resource value: 0x7f010000
			public const int parsingMode = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int percentDisplayMode = 2130771969;
			
			// aapt resource value: 0x7f010011
			public const int resizingMode = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int rowHeaderWidth = 2130771986;
			
			// aapt resource value: 0x7f010020
			public const int scrollingMode = 2130772000;
			
			// aapt resource value: 0x7f010007
			public const int selectAllOnFocus = 2130771975;
			
			// aapt resource value: 0x7f01001f
			public const int selectedIndex = 2130771999;
			
			// aapt resource value: 0x7f010037
			public const int selectionForeground = 2130772023;
			
			// aapt resource value: 0x7f010013
			public const int showRowHeader = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int sortTapAction = 2130771991;
			
			// aapt resource value: 0x7f010035
			public const int useOnDemandPaging = 2130772021;
			
			// aapt resource value: 0x7f010002
			public const int valueChangeMode = 2130771970;
			
			// aapt resource value: 0x7f010021
			public const int verticalOverScrollMode = 2130772001;
			
			// aapt resource value: 0x7f010005
			public const int watermark = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int watermarkColor = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ascending = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Descending = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Drag_and_Drop_Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int DragDown = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DragUp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int error2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int FirstPageIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GroupCollapse = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GroupExpander = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int GroupIcon_Android = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int LastPageIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int NextPageIcon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int PrevPageIcon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ResizingIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Sort = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int SortDescending = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001c
			public const int Relative = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int auto = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int bottom = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int bounce = 2131034132;
			
			// aapt resource value: 0x7f050002
			public const int compute = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int decimalMode = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int doubleMode = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int doubleTap = 2131034120;
			
			// aapt resource value: 0x7f05001a
			public const int horizontal = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int lastCoulmnFill = 2131034136;
			
			// aapt resource value: 0x7f050011
			public const int line = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int moveLast = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int multiple = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int none = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int onKeyFocus = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int onLostFocus = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int onMoved = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int onTap = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int onTouchUp = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int pixel = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int pixelLine = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int selectAll = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int single = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int singleDeSelect = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int singleTap = 2131034121;
			
			// aapt resource value: 0x7f050019
			public const int star = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int top = 2131034134;
			
			// aapt resource value: 0x7f050003
			public const int value = 2131034115;
			
			// aapt resource value: 0x7f05001b
			public const int vertical = 2131034139;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ScrollViewer = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SfDataGrid = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016};
			
			// aapt resource value: 26
			public const int SfDataGrid_allowDraggingColumn = 26;
			
			// aapt resource value: 28
			public const int SfDataGrid_allowDraggingRow = 28;
			
			// aapt resource value: 13
			public const int SfDataGrid_allowEditing = 13;
			
			// aapt resource value: 12
			public const int SfDataGrid_allowGroupExpandCollapse = 12;
			
			// aapt resource value: 21
			public const int SfDataGrid_allowLoadMore = 21;
			
			// aapt resource value: 8
			public const int SfDataGrid_allowMultiSorting = 8;
			
			// aapt resource value: 24
			public const int SfDataGrid_allowPullToRefresh = 24;
			
			// aapt resource value: 2
			public const int SfDataGrid_allowResizingColumn = 2;
			
			// aapt resource value: 6
			public const int SfDataGrid_allowSorting = 6;
			
			// aapt resource value: 30
			public const int SfDataGrid_allowSwiping = 30;
			
			// aapt resource value: 7
			public const int SfDataGrid_allowTriStateSorting = 7;
			
			// aapt resource value: 20
			public const int SfDataGrid_alternationCount = 20;
			
			// aapt resource value: 11
			public const int SfDataGrid_autoExpandGroups = 11;
			
			// aapt resource value: 0
			public const int SfDataGrid_autoGenerateColumns = 0;
			
			// aapt resource value: 32
			public const int SfDataGrid_columnSizer = 32;
			
			// aapt resource value: 14
			public const int SfDataGrid_editTapAction = 14;
			
			// aapt resource value: 15
			public const int SfDataGrid_editorSelectionBehavior = 15;
			
			// aapt resource value: 27
			public const int SfDataGrid_frozenColumnsCount = 27;
			
			// aapt resource value: 29
			public const int SfDataGrid_frozenRowsCount = 29;
			
			// aapt resource value: 33
			public const int SfDataGrid_gridRowHeight = 33;
			
			// aapt resource value: 16
			public const int SfDataGrid_gridSelectionMode = 16;
			
			// aapt resource value: 10
			public const int SfDataGrid_groupingMode = 10;
			
			// aapt resource value: 34
			public const int SfDataGrid_headerRowHeight = 34;
			
			// aapt resource value: 1
			public const int SfDataGrid_indentColumnWidth = 1;
			
			// aapt resource value: 25
			public const int SfDataGrid_isBusy = 25;
			
			// aapt resource value: 23
			public const int SfDataGrid_loadMorePosition = 23;
			
			// aapt resource value: 22
			public const int SfDataGrid_loadMoreText = 22;
			
			// aapt resource value: 31
			public const int SfDataGrid_maxSwipeOffset = 31;
			
			// aapt resource value: 3
			public const int SfDataGrid_resizingMode = 3;
			
			// aapt resource value: 4
			public const int SfDataGrid_rowHeaderWidth = 4;
			
			// aapt resource value: 18
			public const int SfDataGrid_scrollingMode = 18;
			
			// aapt resource value: 17
			public const int SfDataGrid_selectedIndex = 17;
			
			// aapt resource value: 5
			public const int SfDataGrid_showRowHeader = 5;
			
			// aapt resource value: 9
			public const int SfDataGrid_sortTapAction = 9;
			
			// aapt resource value: 19
			public const int SfDataGrid_verticalOverScrollMode = 19;
			
			public static int[] SfDataPager = new int[] {
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023};
			
			// aapt resource value: 5
			public const int SfDataPager_numericButtonBackground = 5;
			
			// aapt resource value: 0
			public const int SfDataPager_numericButtonCount = 0;
			
			// aapt resource value: 3
			public const int SfDataPager_orientation = 3;
			
			// aapt resource value: 2
			public const int SfDataPager_pageCount = 2;
			
			// aapt resource value: 1
			public const int SfDataPager_pageSize = 1;
			
			// aapt resource value: 6
			public const int SfDataPager_selectionForeground = 6;
			
			// aapt resource value: 4
			public const int SfDataPager_useOnDemandPaging = 4;
			
			public static int[] SfNumericTextBox = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 9
			public const int SfNumericTextBox_allowNull = 9;
			
			// aapt resource value: 10
			public const int SfNumericTextBox_borderColor = 10;
			
			// aapt resource value: 12
			public const int SfNumericTextBox_culture = 12;
			
			// aapt resource value: 3
			public const int SfNumericTextBox_enableGroupSeparator = 3;
			
			// aapt resource value: 8
			public const int SfNumericTextBox_fontSize = 8;
			
			// aapt resource value: 6
			public const int SfNumericTextBox_maximumDecimalDigits = 6;
			
			// aapt resource value: 4
			public const int SfNumericTextBox_numberFormat = 4;
			
			// aapt resource value: 13
			public const int SfNumericTextBox_numericTextBoxValue = 13;
			
			// aapt resource value: 0
			public const int SfNumericTextBox_parsingMode = 0;
			
			// aapt resource value: 1
			public const int SfNumericTextBox_percentDisplayMode = 1;
			
			// aapt resource value: 7
			public const int SfNumericTextBox_selectAllOnFocus = 7;
			
			// aapt resource value: 2
			public const int SfNumericTextBox_valueChangeMode = 2;
			
			// aapt resource value: 5
			public const int SfNumericTextBox_watermark = 5;
			
			// aapt resource value: 11
			public const int SfNumericTextBox_watermarkColor = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
